name: semicircular_stage_progress
description: A customizable Flutter widget to display a semicircular stage progress indicator with configurable arcs, colors, and dots.
version: 1.0.2
homepage: https://github.com/karanrana097/semicircular_stage_progress
repository: https://github.com/karanrana097/semicircular_stage_progress

environment:
  sdk: ^3.0.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0



